server:
  port: 5002 # In the project is 5000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankAccount
  kafka:
    producer:
      bootstrap-servers: 192.168.1.131:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer